# Generated by Django 5.2.6 on 2025-09-16 22:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stripe_card', 'Carte bancaire'), ('stripe_sepa', 'Compte bancaire SEPA'), ('paypal', 'Compte PayPal')], max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('paypal_billing_agreement_id', models.CharField(blank=True, max_length=200)),
                ('display_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('customer_request', 'Demande client'), ('product_defect', 'Produit défectueux'), ('wrong_item', 'Mauvais article'), ('not_delivered', 'Non livré'), ('admin_decision', 'Décision administrative'), ('duplicate_payment', 'Paiement en double'), ('fraud', 'Fraude')], max_length=20)),
                ('reason_detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, max_length=200)),
                ('paypal_refund_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('payment_received', 'Paiement reçu'), ('refund_issued', 'Remboursement émis'), ('vendor_payout', 'Paiement vendeur'), ('commission_earned', 'Commission perçue'), ('fee_charged', 'Frais prélevés'), ('adjustment', 'Ajustement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('paid', 'Payé'), ('failed', 'Échec'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payout_method', models.CharField(default='bank_transfer', max_length=50)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=200)),
                ('paypal_payout_batch_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paiement vendeur',
                'verbose_name_plural': 'Paiements vendeurs',
                'db_table': 'vendor_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('stripe_card', 'Carte bancaire (Stripe)'), ('stripe_sepa', 'Virement SEPA (Stripe)'), ('paypal', 'PayPal'), ('bank_transfer', 'Virement bancaire'), ('admin', 'Paiement manuel (Admin)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé'), ('partially_refunded', 'Partiellement remboursé')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=200)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_exp_month', models.CharField(blank=True, max_length=2)),
                ('card_exp_year', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
